# Numpy
<li>Numpy is a numarical computiig library for python</li>
<li>Numpy support multi dimensional array and matrices</li>
<li>It has a lot of built in mathematical function</li>

In [2]:
!pip install numpy

In [3]:
import numpy as np

# Why numpy?
<li>Perform fast oprations (because of vectorization)</li>
<li>numpy array treated as a vectors and mitrices from linear algebra</li>


In [5]:
lst=[2,3,56,7,6,4,3]

In [6]:
%timeit [i**2 for i in lst]

897 ns ± 277 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
arr=np.array(lst)

In [8]:
arr

array([ 2,  3, 56,  7,  6,  4,  3])

In [9]:
%timeit arr**2

1.32 μs ± 81.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
lst

[2, 3, 56, 7, 6, 4, 3]

In [11]:
# if a want to add 1 elment of this vector
lst +[1]

[2, 3, 56, 7, 6, 4, 3, 1]

In [12]:
# but it is possible in numpy array
arr + [1]

array([ 3,  4, 57,  8,  7,  5,  4])

# Numpy Bsics
<b>array:<b>
Fundamentals elment in numpy is homogenous array.Numpy array can be 1D , 2D,3D.....nD
<li>Different ways to create np array:</li>
<ol>np.array()</ol>
<ol>np.arange()</ol>

In [14]:
l=[2,3,4,5,7,7,8]

In [15]:
np_arr=np.array(l)

In [16]:
np_arr

array([2, 3, 4, 5, 7, 7, 8])

In [17]:
type(np_arr)

numpy.ndarray

In [18]:
# to check what type of array like 1d,2dor 3d etc..
np_arr.ndim

1

In [19]:
# to check how many elemnts in array we will use the shape property
np_arr.shape

(7,)

# Another way of creating np array

In [208]:
new_arr=np.arange(3,11,2)  # start with 3 and iterate over 11 and 11 not be included it is excluded and the step size is 2

In [210]:
new_arr

array([3, 5, 7, 9])

# To create 2D array

In [213]:
lst_2D=[[2,3,4],[5,6,7],[7,8,9]]

In [215]:
arr_2D=np.array(lst_2D)

In [217]:
arr_2D

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 9]])

In [219]:
arr_2D.shape # to check the element in the array

(3, 3)

In [221]:
# to check what type of array 
arr_2D.ndim

2

<h2> special array in Numpy</h2>
<li>zeros()</li> 
<li>ones()</li> 
<li>diag()</li> 
<li>identity</li>

In [30]:
# to create a zero matrix
np.zeros((3,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Indexing in array

In [35]:
#to ctrate the random matrix
np.random.randint(0,20)

7

In [36]:
new_arr=np.random.randint(0,20,(3,4))

In [37]:
new_arr

array([[13, 17, 18,  1],
       [11,  1,  8, 15],
       [ 2, 18,  8, 12]])

In [38]:
# to acess the first row
new_arr[0]

array([13, 17, 18,  1])

In [39]:
# to acess the second last element or row 
new_arr[-2]

array([11,  1,  8, 15])

In [40]:
 # first element 
print(new_arr[0,0])

# last element
print(new_arr[-1,-1])
#last elememt in second row
print(new_arr[1,3])

13
12
15


# Array slicing

In [42]:
new_arr

array([[13, 17, 18,  1],
       [11,  1,  8, 15],
       [ 2, 18,  8, 12]])

In [43]:
# syntax of array slicing
 #arr[start_row_idx:end_row_idx+1,start_col_idx:end_col_idx+1]

In [44]:
new_arr[1:,1:]

array([[ 1,  8, 15],
       [18,  8, 12]])

In [45]:
# only 2nd coloum
new_arr[:,1]

array([17,  1, 18])

In [46]:
# you can also replace the element 
new_arr[0,0]=2

In [47]:
new_arr

array([[ 2, 17, 18,  1],
       [11,  1,  8, 15],
       [ 2, 18,  8, 12]])

# Masking

In [49]:
mask=new_arr>10  # whereever the element is grater than 10 it should be true
print(mask)  # the mask will gives us the boolean value

[[False  True  True False]
 [ True False False  True]
 [False  True False  True]]


In [50]:
np.sum(mask) # it will gives us the sum of all true 

6

In [51]:
new_arr[mask]

array([17, 18, 11, 15, 18, 12])

In [52]:
new_arr[1:,2:]=0 # if you want to make last few elments will be zero

In [53]:
new_arr

array([[ 2, 17, 18,  1],
       [11,  1,  0,  0],
       [ 2, 18,  0,  0]])

# Basic operations on array

In [55]:
a= np.array([11,12,13,14])
b=np.arange(1,5)

In [56]:
a

array([11, 12, 13, 14])

In [57]:
b

array([1, 2, 3, 4])

In [58]:
a+b

array([12, 14, 16, 18])

In [59]:
a-b

array([10, 10, 10, 10])

In [60]:
a*b

array([11, 24, 39, 56])

In [61]:
b**2

array([ 1,  4,  9, 16])

In [62]:
#masking
a>5

array([ True,  True,  True,  True])

In [63]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

# Matix product

In [65]:
A=np.random.randint(0,5,(3,4))
B=np.random.randint(0,5,(4,2))

In [66]:
A

array([[3, 2, 0, 1],
       [4, 4, 2, 2],
       [3, 2, 0, 0]])

In [67]:
B

array([[4, 3],
       [2, 4],
       [2, 2],
       [4, 1]])

In [68]:
# multiplication matrix
np.dot(A,B)

array([[20, 18],
       [36, 34],
       [16, 17]])

# More Operations on array

In [70]:
A=np.arange(0,24)

In [71]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
A=A.reshape(6,4)

In [73]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
#square root of arraya
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [75]:
np.sum(A) # sum of array

276

In [76]:
np.max(A) # max value in array

23

In [77]:
np.min(A) # min value in array

0

In [78]:
np.mean(A)

11.5

In [79]:
np.median(A)

11.5

In [80]:
np.std(A)

6.922186552431729

In [81]:
# you want to sum column wise then
np.sum(A,axis=1)

array([ 6, 22, 38, 54, 70, 86])

# Shape manupulation

In [83]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [84]:
# to flat the array
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [85]:
A.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [86]:
# it convert column to rows and rows to column
A.transpose()  # or you can write  np.transpose(A)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

# Stacking of array  
<li>vstack</li> 
<li>hstack</li>  

In [88]:
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))

In [89]:
a

array([[8, 3],
       [1, 2]])

In [90]:
b

array([[1, 7],
       [3, 1]])

In [91]:
np.hstack((a,b)) # joint matrix horizontally

array([[8, 3, 1, 7],
       [1, 2, 3, 1]])

In [92]:
np.vstack((a,b)) # joint matrix vertically

array([[8, 3],
       [1, 2],
       [1, 7],
       [3, 1]])

# Broadcasting
<li> first rule of numpy::- 2 Array can perform operation  only when they have same shapes</li>
<li>broadcasting let 2 arrays of different shapes to do some operations </li>
<li>A small array will repeat itself, and convert to the same shape as of another array</li>

In [94]:
A=np.random.randint(0,10,(3,3))
b=np.array([2,3,4])

In [95]:
A

array([[9, 4, 7],
       [5, 8, 4],
       [7, 1, 2]])

In [96]:
b

array([2, 3, 4])

In [97]:
A+b

array([[11,  7, 11],
       [ 7, 11,  8],
       [ 9,  4,  6]])

In [98]:
b.T

array([2, 3, 4])

In [99]:
A+b.T

array([[11,  7, 11],
       [ 7, 11,  8],
       [ 9,  4,  6]])

In [100]:
print(A.shape,b.shape)

(3, 3) (3,)


In [101]:
A

array([[9, 4, 7],
       [5, 8, 4],
       [7, 1, 2]])

In [102]:
A+4

array([[13,  8, 11],
       [ 9, 12,  8],
       [11,  5,  6]])

# Vectorization
perform operation directly on array

In [104]:
p1=np.array([1,2])
p2=np.array([5,5])

In [105]:
s=0
for i in range(2):
    s+= (p2[i]-p1[i])**2
print(s**0.5)

5.0


In [106]:
np.sqrt(np.sum((p2-p1)**2))

5.0

In [107]:
s=np.arange(1,17,2)

In [108]:
s

array([ 1,  3,  5,  7,  9, 11, 13, 15])